name: Unittesting

on:
  push:
    branches:
      - main
      
jobs:
  build-Unittesting:
    runs-on: self-hosted
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build and Run Docker Compose
        run: |
          docker-compose -f _ci.yml up --build -d

      - name: Run Tests
        run: |
          docker-compose -f _ci.yml run --rm app-test || true

      - name: Copy Coverage Report
        run: |
          container_id=$(docker-compose -f _ci.yml ps -q app-test)
          docker cp $container_id:/app/coverage/coverage.xml .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
